### ISSUE TITLE
Network Connectivity Alarm

### ISSUE THREAD

**Issue by remiscarlet** [Yukkuricraft/Yukkuricraft#26]
Might be better in a different repo.

Have GHA or some other mechanism check for/send a heartbeat to the server. If it's inaccessible for 5-10 minutes send an alarm.

ISP's and self-hosting. Sadge

**Comment by Taiyou06** [comment]
If every proxy will have their each DiscordSRV plugin it's not necessary as DiscordSRV has built in Heartbeat check. Plugin could be modified to show the instance name of the docker container so sysadmins would know what server has a issue.

**Comment by remiscarlet** [comment]
This is handled with AWS CloudWatch Alarms and Discord webhooks now using metrics emitted from https://github.com/Yukkuricraft/UnifiedMetrics
